// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEbBDC0jY6xp1xSMxz-FYq8jvsIb6J14k',
    appId: '1:1008207391772:android:6b4151d6cdfd579cff83d9',
    messagingSenderId: '1008207391772',
    projectId: 'habitos-app-1b86b',
    storageBucket: 'habitos-app-1b86b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYYLjYAQhSqBXPp9mJNyUbSNi2qffU314',
    appId: '1:1008207391772:ios:b595f38a55782300ff83d9',
    messagingSenderId: '1008207391772',
    projectId: 'habitos-app-1b86b',
    storageBucket: 'habitos-app-1b86b.firebasestorage.app',
    androidClientId: '1008207391772-033hh77pe69uqlchjaupe98o24qs1t35.apps.googleusercontent.com',
    iosClientId: '1008207391772-l7ahuk5g4rtun22t5g84ea2lp8oa9bam.apps.googleusercontent.com',
    iosBundleId: 'br.com.habitusapp',
  );

}